language: java

sudo: false

jdk:
  - oraclejdk8

branches:
  only:
    - master
  
env:
  global:
    - GH_REF=github.com/hdbeukel/james.git
    - SONATYPE_USERNAME=hdbeukel
    - secure: "rvXkoy0tElQmFUavN9oMfyctY+ZHKat+U73hs3q3xKl42JF+NEccPWESgsrccmwQ4AwJ9XKLM8Su2J4GbJ8MBcdLsdljl9uvCv9ZjxLBGu3+Fc4ot4SDVDIKHE+45yz13CSH5gm4n4ZmcO1SK6H2pYbRSTuFYBsIQiN+SoeMK0I="
    - secure: "IOkjlySFtey69gIACF0QqaYlZPwQ+FzRdzXNRwEo0mmCNyflDBKpMoopD+qHdq1eEGFFoWXQ3e747Ff1ZpOTy/A3xtn0399LMgHOpKdgU19x85JPmnn+Nv65iICIcGMlt2KWC/yOq5CMcXfKIjsaPwFWY+UAV395S5lvXZimL1Y="
  
before_install: cd james

after_success:
  - mvn coveralls:report
  - python ../.travis/add-sonatype-server.py
  - mvn clean deploy -DskipTests=true --settings ~/.m2/mySettings.xml
  - git clone --branch=gh-pages git://github.com/hdbeukel/james.git site
  - cd site
  - cp -R ../james-core/target/apidocs/* api/core/snapshot/
  - cp -R ../james-extensions/target/apidocs/* api/ext/snapshot/
  - git config user.name "Herman De Beukelaer"
  - git config user.email "herman.debeukelaer@gmail.com"
  - git add api
  - git commit -m "updated snapshot APIs"
  - git push "https://${GH_TOKEN}@${GH_REF}" gh-pages


