# Build settings
markdown: kramdown
permalink: pretty

# Custom variables

# used for links to latest snapshot JARs (core, extensions) and ZIP (examples) at Sonatype OSSRH
core-snapshot: 1.1-SNAPSHOT
extensions-snapshot: 1.0.1-SNAPSHOT
examples-snapshot: 1.0.1-SNAPSHOT

# used for links to latest stable releases and corresponding APIs
core-latest-stable: 0.2
extensions-latest-stable: 0.2.1
examples-latest-stable: 0.2.1

# used for links to all versions of APIs
core-all-stable:       [   '', 0.2, 0.1]
extensions-all-stable: [0.2.1, 0.2, 0.1]
